// Distributed under the MIT License.
// See LICENSE.txt for details.

#pragma once


#include <limits>
#include <memory>

#include <blaze/Blaze.h>
#include "DataStructures/CachedTempBuffer.hpp"
#include "DataStructures/Tensor/EagerMath/DeterminantAndInverse.hpp"
#include "Elliptic/Systems/BnsInitialData/FirstOrderSystem.hpp"
#include "Elliptic/Systems/BnsInitialData/Tags.hpp"
#include "IO/Exporter/Exporter.hpp"
#include "IO/Exporter/InterpolateToPoints.hpp"
#include "NumericalAlgorithms/LinearOperators/PartialDerivatives.hpp"
#include "Options/String.hpp"
#include "PointwiseFunctions/GeneralRelativity/Tags.hpp"
#include "PointwiseFunctions/Hydro/EquationsOfState/EquationOfState.hpp"
#include "PointwiseFunctions/Hydro/InitialData/IrrotationalBns.hpp"
#include "PointwiseFunctions/Hydro/Tags.hpp"
#include "PointwiseFunctions/InitialDataUtilities/Background.hpp"
#include "PointwiseFunctions/InitialDataUtilities/InitialGuess.hpp"
#include "Utilities/Serialization/CharmPupable.hpp"
#include "Utilities/TMPL.hpp"
#include "Utilities/TaggedTuple.hpp"

/// \cond
namespace PUP {
class er;
}  // namespace PUP
/// \endcond

namespace BnsInitialData::AnalyticData {

/*!
 * \brief Hydro initial data generated by SpEC.
 *
 * This class loads spectre volume data, in particular it interpolates the following quantites:
 *
 * - "SpatialMetric": spatial metric
 * - "ExtrinsicCurvature": (lower) extrinsic curvature
 * - "Lapse": lapse
 * - "Shift": (upper) shift
 * - "RestMassDensity": rest mass density
 * - "LowerSpatialFourVelocity": lower spatial four-velocity
 *
 * The remaining hydro quantities are computed from the interpolated data and
 * the equation of state.
 * The magnetic field is set to zero and the electron fraction is set to a
 * constant read from the input file.
 */
template <size_t ThermodynamicDim>
class SpectreData : public elliptic::analytic_data::Background,
                 public elliptic::analytic_data::InitialGuess {
 public:
  using equation_of_state_type =
      EquationsOfState::EquationOfState<true, ThermodynamicDim>;

  template <typename DataType>
  using variable_tags =
      tmpl::list<::BnsInitialData::Tags::VelocityPotential<DataType>>;
  template <typename DataType>
  using background_tags = tmpl::list<
      hydro::Tags::RestMassDensity<DataVector>,
      gr::Tags::InverseSpatialMetric<DataType, 3>,
      gr::Tags::SpatialChristoffelSecondKindContracted<DataType, 3>,
      gr::Tags::Lapse<DataType>,
      ::Tags::deriv<gr::Tags::Lapse<DataType>,
                    tmpl::integral_constant<size_t, 3>, Frame::Inertial>,
      gr::Tags::Shift<DataType, 3>,
      ::Tags::deriv<gr::Tags::Shift<DataType, 3>,
                    tmpl::integral_constant<size_t, 3>, Frame::Inertial>,
      BnsInitialData::Tags::RotationalShift<DataType>,
      BnsInitialData::Tags::DerivLogLapseTimesDensityOverSpecificEnthalpy<
          DataType>,
      BnsInitialData::Tags::RotationalShiftStress<DataType>>;
  template <typename DataType>
  using tags = tmpl::append<background_tags<DataType>, variable_tags<DataType>>;

  struct VolumeFileGlob {
    using type = std::string;
    static constexpr Options::String help = {
        "Path to a directory of data produced by SpEC. The directory is "
        "expected to contain 'GrDomain.input' and 'Vars*.h5' files for all the "
        "subdomains in GrDomain.input."};
  };
  struct SubfileName{
    using type = std::string;
    static constexpr Options::String help =
        "Name of the subfile to read from. If not provided, the first subfile "
        "found will be used.";
  };
  struct ObservationStep{
    using type = int;
    static constexpr Options::String help =
        "The observation step to use for interpolation.";
  };

  struct DensityCutoff {
    using type = double;
    static constexpr Options::String help =
        "Where the density is below this cutoff the fluid variables are set to "
        "vacuum (zero density, pressure, energy and velocity, unit Lorentz "
        "factor and enthalpy). ";
  };
  struct OrbitalAngularVelocity {
    using type = double;
    static constexpr Options::String help =
        "The initial angular velocity of the binary orbit";
  };

  using options = tmpl::list<
      VolumeFileGlob, SubfileName, ObservationStep,
      ::hydro::OptionTags::InitialDataEquationOfState<true, ThermodynamicDim>,
      DensityCutoff, OrbitalAngularVelocity,
      ::BnsInitialData::Tags::OptionTags::EulerEnthalpyConstant>;

  static constexpr Options::String help = {"Initial data read from spectre" 
                                            "volume data"};

  SpectreData() = default;
  SpectreData(const SpectreData& rhs);
  SpectreData& operator=(const SpectreData& rhs);
  SpectreData(SpectreData&& /*rhs*/) = default;
  SpectreData& operator=(SpectreData&& /*rhs*/) = default;
  ~SpectreData() override = default;

  SpectreData(std::string volume_file_glob, std::string subfile_name, 
            int observation_step,
           std::unique_ptr<equation_of_state_type> equation_of_state,
           double density_cutoff, double orbital_angular_velocity,
           double euler_enthalpy_constant);

  auto get_clone() const
      -> std::unique_ptr<elliptic::analytic_data::Background>;

  /// \cond
  explicit SpectreData(CkMigrateMessage* msg);
  using PUP::able::register_constructor;
  WRAPPED_PUPable_decl_template(SpectreData);
  /// \endcond
  const equation_of_state_type& equation_of_state() const {
    return *equation_of_state_;
  }
  // Deriv of velocity potential is only
  // used for validation
  template <typename DataType>
  tnsr::i<DataType, 3> deriv_of_velocity_potential(
      const tnsr::I<DataType, 3, Frame::Inertial>& x) const;

  // The velocity potential is used in the initial guess
  template <typename DataType>
  tuples::TaggedTuple<Tags::VelocityPotential<DataType>> variables(
      const tnsr::I<DataType, 3, Frame::Inertial>& x,
      tmpl::list<Tags::VelocityPotential<DataType>> /*meta*/) const;
  // The fixed sources are used in initialization
  template <typename DataType>
  tuples::TaggedTuple<::Tags::FixedSource<Tags::VelocityPotential<DataType>>>
  variables(const tnsr::I<DataType, 3, Frame::Inertial>& x, const Mesh<3>& mesh,
            const InverseJacobian<DataType, 3, Frame::ElementLogical,
                                  Frame::Inertial>& inv_jacobian,
            tmpl::list<::Tags::FixedSource<
                Tags::VelocityPotential<DataType>>> /*meta*/) const;
  template <typename DataType>
  tuples::TaggedTuple<gr::Tags::InverseSpatialMetric<DataType, 3>> variables(
      const tnsr::I<DataType, 3, Frame::Inertial>& x,
      tmpl::list<gr::Tags::InverseSpatialMetric<DataType, 3>> /*meta*/) const;
  template <typename DataType>
  tuples::tagged_tuple_from_typelist<background_tags<DataType>> variables(
      const tnsr::I<DataType, 3, Frame::Inertial>& x, const Mesh<3>& mesh,
      const InverseJacobian<DataType, 3, Frame::ElementLogical,
                            Frame::Inertial>& inv_jacobian,
      background_tags<DataType> /*meta*/) const;

  // NOLINTNEXTLINE(google-runtime-references)
  void pup(PUP::er& /*p*/) override;

 private:
  /// These quantities are supported for interpolation from SpEC
  template <typename DataType>
  using interpolated_tags = tmpl::list<
      // GR quantities
      gr::Tags::SpatialMetric<DataType, 3>,
      gr::Tags::Lapse<DataType>,
      gr::Tags::Shift<DataType, 3>,
      // Hydro quantities
      hydro::Tags::RestMassDensity<DataType>,
      hydro::Tags::LowerSpatialFourVelocity<DataType, 3>>;


  template <typename DataType>
  tuples::tagged_tuple_from_typelist<interpolated_tags<DataType>>
  interpolate_from_spectre(const tnsr::I<DataType, 3>& x) const;

  std::string volume_file_glob_{};
  std::string subfile_name_{};

  std::unique_ptr<equation_of_state_type> equation_of_state_{nullptr};
  double density_cutoff_ = std::numeric_limits<double>::signaling_NaN();
  double orbital_angular_velocity_ =
      std::numeric_limits<double>::signaling_NaN();
  double euler_enthalpy_constant_ =
      std::numeric_limits<double>::signaling_NaN();
  int observation_step_ = -1;


};

}  // namespace BnsInitialData::AnalyticData
